apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  auth-secret: {{ .Values.auth.secret | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.database.username .Values.database.password .Values.database.host (.Values.database.port | int) .Values.database.name | b64enc | quote }}
  api-gateway-secret: {{ .Values.secrets.apiGatewaySecret | default "change-this-gateway-secret" | b64enc | quote }}
  internal-service-secret: {{ .Values.secrets.internalServiceSecret | default "change-this-service-secret" | b64enc | quote }}
