apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: micro-services-blog
spec:
  selector:
    matchLabels:
      app: micro-services-blog
  template:
    metadata:
      labels:
        app: micro-services-blog
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"