# ng uses node internally and there's not really a clean way around it
# we can still use bun for everything else though
FROM docker.io/imbios/bun-node:latest

WORKDIR /app

COPY . .

RUN bun install

EXPOSE 4200
CMD ["bun", "run", "start", "--host", "0.0.0.0"]