apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_PASSWORD
              value: localdevpassword
            - name: POSTGRES_USER
              value: user
          image: docker.io/postgres:latest
          name: db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
