apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-blog
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      service: keycloak
  template:
    spec:
      containers:
      - name: keycloak
        args: ["start-dev"]
        env:
        - name: KC_LOG_LEVEL
          value: "DEBUG"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_CACHE
          value: "local"
        # Remove JGroups clustering
        - name: JAVA_OPTS_APPEND
          value: ""