apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  microblog-realm.json: |
    {
      "realm": "microblog",
      "enabled": true,
      "registrationAllowed": true,
      "registrationEmailAsUsername": true,
      "rememberMe": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "sslRequired": "none",
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 60,
      "quickLoginCheckMilliSeconds": 1000,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 5,
      "defaultRole": {
        "name": "user",
        "description": "Default role for all users"
      },
      "requiredCredentials": ["password"],
      "passwordPolicy": "length(8)",
      "clients": [
        {
          "clientId": "microblog-frontend",
          "name": "Microblog Frontend Application",
          "description": "The Angular frontend for the microblog platform",
          "rootUrl": "http://localhost:4200",
          "adminUrl": "http://localhost:4200",
          "baseUrl": "/",
          "enabled": true,
          "publicClient": true,
          "protocol": "openid-connect",
          "redirectUris": [
            "http://localhost:4200/*",
            "http://localhost:3000/*",
            "http://microblog.local/*"
          ],
          "webOrigins": [
            "http://localhost:4200",
            "http://localhost:3000",
            "http://microblog.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "attributes": {
            "pkce.code.challenge.method": "S256",
            "post.logout.redirect.uris": "http://localhost:4200/*##http://localhost:3000/*",
            "oauth2.device.authorization.grant.enabled": "false",
            "oidc.ciba.grant.enabled": "false"
          }
        },
        {
          "clientId": "microblog-api",
          "name": "Microblog API Gateway",
          "description": "The API gateway service for backend authentication",
          "enabled": true,
          "publicClient": false,
          "protocol": "openid-connect",
          "secret": "your-api-gateway-secret-change-this",
          "serviceAccountsEnabled": true,
          "authorizationServicesEnabled": false,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "attributes": {
            "oauth2.device.authorization.grant.enabled": "false",
            "oidc.ciba.grant.enabled": "false",
            "use.refresh.tokens": "true",
            "client_credentials.use_refresh_token": "false"
          }
        }
      ],
      "users": [
        {
          "username": "testuser",
          "email": "test@example.com",
          "emailVerified": true,
          "enabled": true,
          "firstName": "Test",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "realmRoles": ["user"],
          "clientRoles": {}
        },
        {
          "username": "admin",
          "email": "admin@example.com",
          "emailVerified": true,
          "enabled": true,
          "firstName": "Admin",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["user", "admin"],
          "clientRoles": {}
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user with standard permissions",
            "composite": false
          },
          {
            "name": "admin",
            "description": "Administrator with elevated permissions",
            "composite": false
          },
          {
            "name": "moderator",
            "description": "Content moderator permissions",
            "composite": false
          }
        ]
      },
      "scopeMappings": [
        {
          "client": "microblog-frontend",
          "roles": ["user", "admin"]
        }
      ],
      "clientScopeMappings": {},
      "browserSecurityHeaders": {
        "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
        "xContentTypeOptions": "nosniff",
        "xRobotsTag": "none",
        "xFrameOptions": "SAMEORIGIN",
        "xXSSProtection": "1; mode=block",
        "strictTransportSecurity": "max-age=31536000; includeSubDomains"
      },
      "smtpServer": {},
      "eventsEnabled": false,
      "eventsListeners": ["jboss-logging"],
      "enabledEventTypes": [],
      "adminEventsEnabled": false,
      "adminEventsDetailsEnabled": false,
      "internationalizationEnabled": true,
      "supportedLocales": ["en"],
      "defaultLocale": "en",
      "authenticationFlows": [],
      "authenticatorConfig": [],
      "requiredActions": [],
      "browserFlow": "browser",
      "registrationFlow": "registration",
      "directGrantFlow": "direct grant",
      "resetCredentialsFlow": "reset credentials",
      "clientAuthenticationFlow": "clients"
    }