apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        # Use secret for password instead of hardcoded value
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak-secrets
        #       key: DB_PASSWORD
        
        # Development-specific PostgreSQL configuration
        - name: POSTGRES_INITDB_ARGS
          value: "--encoding=UTF8 --locale=en_US.UTF-8"
        
        # Enable query logging for development debugging
        - name: POSTGRES_ARGS
          value: "-c log_statement=all -c log_connections=on"
      
      # Add volume for local development persistence
      volumes:
      - name: postgres-storage
        hostPath:
          path: /host-mount/services/keycloak/.postgres
          type: DirectoryOrCreate