apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: microservices-blog
spec:
  selector:
    matchLabels:
      app: microservices-blog
  template:
    metadata:
      labels:
        app: microservices-blog
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        ports:
        - containerPort: 3000
          name: http
        # envs are added via configMap in overlays
        # Uncomment below to hardcode env vars (not recommended)
        # env:
        # - name: NODE_ENV
        #   value: development
        # - name: PORT
        #   value: "3000"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi