POST http://localhost:3000/
content-type: application/json

{
  "title": "Created Post",
  "author": "John Doe",
  "content": "This is a post"
}

###

GET http://localhost:3000/

###

GET http://localhost:3000/filter?take=2

###

GET http://localhost:3000/filter?searchString=Created&nbsp;Post

###

GET http://localhost:3000/1

###

PUT http://localhost:3000/1/content
Content-Type: application/json

{
  "content": "Content for post #1"
}

###

DELETE http://localhost:3000/6