apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-services-blog
  template:
    metadata:
      labels:
        app: micro-services-blog
    spec:
      containers:
      - name: frontend
        image: frontend:dev
        ports:
        - containerPort: 4200
          name: dev-server
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits:
            memory: "1024Mi"
            cpu: "4000m"
        # Mount the entire service directory into the container
        volumeMounts:
        - name: code
          mountPath: /app

      # Define the volume that maps to your local filesystem
      volumes:
      - name: code
        hostPath:
          # Path relative to where you run kubectl/docker-compose
          path: /host-mount/services/frontend
          type: Directory