apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Start with the base configuration
resources:
- ../../base

# Apply our local development patch
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: auth-service
- path: postgres-deployment-patch.yaml
  target:
    kind: Deployment 
    name: auth-postgres

# Local-specific labels
# commonLabels:
#   variant: local-dev

# replace with labels because commonLabels is deprecated
labels:
- includeSelectors: true
  pairs:
    environment: local
    variant: local-dev

secretGenerator:
- name: auth-service-secrets
  envs:
  - .env

# configMapGenerator:
# - name: auth-service-config
#   envs:
#   - .env