apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-blog
  name: auth-pg
spec:
  selector:
    matchLabels:
      app: auth-pg
      service: auth-service
  template:
    spec:
      # Add the volume definition for local development
      volumes:
      - name: postgres-storage
        hostPath:
          path: /host-mount/services/auth-service/.postgres
          type: DirectoryOrCreate