apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-blog
  name: auth-service
  labels:
    app: auth-backend
    service: auth-service
spec:
  selector:
    matchLabels:
      app: auth-backend
      service: auth-service
  template:
    metadata:
      labels:
        app: auth-backend
        service: auth-service
    spec:
      initContainers:
      # This container runs before the main auth-service container
      - name: wait-for-postgres
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z auth-pg 5432; do
            echo "PostgreSQL is not ready yet. Waiting..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi