apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
  labels:
    app: micro-services-blog
spec:
  selector:
    app: micro-services-blog
  ports:
  - port: 5432
    targetPort: postgres
  type: ClusterIP