apiVersion: v1
kind: Service
metadata:
  namespace: microservices-blog
  name: auth-pg
  labels:
    app: auth-pg
    service: auth-service
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: auth-pg
    service: auth-service