apiVersion: v1
kind: Service
metadata:
  namespace: microservices-blog
  name: auth-service
spec:
  selector:
    app: auth-backend
    service: auth-service
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP  # Internal service, only accessible within cluster