apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: micro-services-blog
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP  # Internal service, only accessible within cluster