services:
  spinroute-auth-service:
    build:
      context: .
      dockerfile: Containerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      # - NODE_ENV=production
      - DATABASE_URL=postgres://userlocaldevpassworddb:5432/auth_db
    depends_on:
      - db
  db:
    image: docker.io/postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"