apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-blog
  name: posts-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-pg
      service: posts-service
  template:
    metadata:
      labels:
        app: posts-pg
        service: posts-service
    spec:
      containers:
        - name: posts-pg
          image: 'postgres:15-alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: posts-pg-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      # volumes:
      # - name: postgres-storage
      #   emptyDir: {}
        # hostPath:
        #   path: /host-mount/services/posts-service/.postgres
        #   type: DirectoryOrCreate