apiVersion: v1
kind: Service
metadata:
  name: posts-service
  labels:
    app: micro-services-blog
spec:
  selector:
    app: micro-services-blog
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP