apiVersion: v1
kind: Service
metadata:
  namespace: microservices-blog
  name: posts-service
spec:
  selector:
    app: posts-backend
    service: posts-service
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP  # Internal service, only accessible within cluster