apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- postgres-deployment.yaml
- postgres-service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: microblog-platform
